version: "3.3"
name: "electric_quickstart"

services:
  electric:
    image: electricsql/electric
    environment:
      DATABASE_URL: postgresql://postgres:@host.docker.internal:54321/electric?sslmode=disable
    ports:
      - "3000:3000"
